### ISSUE TITLE
UI behaves poorly with Windows UI scaling

### ISSUE THREAD

**Issue by tomshackell** [spencershepard/RotorOps#21]
The UI doesn't render very well on my 4K screen with 200% UI scaling set in Windows settings.

![image](https://user-images.githubusercontent.com/4047652/152758720-eda27ba7-9e1c-40d0-9168-76d33874d92e.png)

Note that resizing the window also doesn't help.

**Comment by spencershepard** [comment]
Hi @tomshackell please check this latest build and let me know if the UI works for you.  #27
