### ISSUE TITLE
UI window doesn't fit some screen resolutions

### ISSUE THREAD

**Issue by JoaoMuas** [spencershepard/RotorOps#24]
Please add a scrollable bar to width and height so UI window can be manually adjusted.
Thanks for the good work.

**Comment by spencershepard** [comment]
Hi @JoaoMuas please check this latest build and let me know if the UI works for you.  #27

**Comment by JoaoMuas** [comment]
It fits my screen perfectly, thanks a lot!!

**Comment by JoaoMuas** [comment]
It's perfect!! Thanks!!
