### ISSUE TITLE
Generated Missions in User\Saved Games\DCS.openbeta\Missions directory

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [spencershepard/RotorOps#28]
Would be great to have the option of having the generated missions automatically go into a directory of choice such as 

   ...\User\Saved Games\DCS.openbeta\Missions 

I have other missions generated by Liberation and Briefing Room and they are all there in one convenient place.

**Comment by LombardiDaniel** [comment]
I took a look into the code, should be somewhat of an easy fix, just change the `cls.output` in MissionGenerator.py, line `47`. I have absolutely no idea how to change the UI though, to make it dynamic.

I imagine you may be able to just change manually it as a temporary fix.

**Comment by spencershepard** [comment]
Hi guys, this was in the works and is part of our beta release today. (https://github.com/spencershepard/RotorOps/releases/tag/1.1.2)
