### ISSUE TITLE
Marianas Rota Landing - Unlimited Weapons Disabled

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [spencershepard/RotorOps#31]
I noticed in the above mission, unlimited weapons is not working. The other missions leave that user option alone. Anyway to turn it back on? Thks.

**Comment by spencershepard** [comment]
RotorOps uses mission templates that can contain any number of settings, variables, triggers, etc etc and we encourage people to create their own. Issues such as this don't really have anything to do with the core of RotorOps. Mission specific issues or suggestions would probably be best discussed on our Discord: https://discord.gg/axV72dZrvY
