### ISSUE TITLE
Marianas Rota Landing - Missing Loadouts 

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [spencershepard/RotorOps#32]
Many loadout options are missing.
![image](https://user-images.githubusercontent.com/94265170/164969917-10d287a9-0d8a-4276-a892-c6d15309919c.png)

**Comment by spencershepard** [comment]
@GrEaSeLiTeNiN RotorOps doesn't set your available loadouts in any way, and I don't think we do anything to restrict available loadouts either.  Please let me know if you've resolved this.

**Comment by spencershepard** [comment]
@GrEaSeLiTeNiN 

Oh, I see.  The mission has a historical setting that is restricting the hellfire loadouts.  You can disable the restriction with the wristwatch icon, lower center of your screenshot.   

RotorOps uses mission templates that can contain any number of settings, variables, triggers, etc etc and we encourage people to create their own and may not have much to do with the core of RotorOps0.  Mission specific issues would probably be best discussed on our Discord:  https://discord.gg/axV72dZrvY
