### ISSUE TITLE
Persian Gulf - Black Hawk Down Pt. 1

### ISSUE THREAD

**Issue by GrEaSeLiTeNiN** [spencershepard/RotorOps#43]
Two identical missions listed. Any difference?
![ROps](https://user-images.githubusercontent.com/94265170/213196622-ec8e1ea7-2f50-483f-87d4-e6e55fd1891f.jpg)

**Comment by spencershepard** [comment]
No difference at all.  In fact there is only one scenario file.  Not sure why it gets listed twice.  This is an issue to look into, thanks.

**Comment by fercyful** [comment]
Same is happening with Part 2. I have listed twice. Used the RotorOps Updater. Thanks
